version: "3.9"

services:
  back:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

