version: "3.9"

services:
  backend:
    build: .
    container_name: nelikvid_backend
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
    restart: unless-stopped
