# Generated by Django 5.2.5 on 2025-08-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_category_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('popular', 'Популярные товары'), ('women', 'Женщинам'), ('men', 'Мужчинам'), ('kids', 'Детям')], max_length=20),
        ),
    ]
