# Generated by Django 5.2.5 on 2025-08-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('popular', 'Популярные товары'), ('women', 'Женщинам'), ('men', 'Мужчинам'), ('kids', 'Детям'), ('soon', 'Скоро')], max_length=20),
        ),
    ]
