# Generated by Django 5.2.5 on 2025-08-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
