# Generated by Django 5.2.5 on 2025-08-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_category',
        ),
    ]
